# Generated by Django 5.2.1 on 2025-06-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Класс автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Автомобиль')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='lab3.carclass', verbose_name='Класс автомобиля')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='lab3.manufacturer', verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='CarParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Параметр')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab3.car', verbose_name='Автомобиль')),
            ],
        ),
    ]
